### ISSUE TITLE
"Ambiguous use of Promise.pipe(to:)" error building with Xcode 10.2 Beta 1 in Swift 4 mode

### ISSUE THREAD

**Issue by JaviSoto** [lilyball/Tomorrowland#31]
I think this is because of the Swift 5 change special-casing Swift.Error, but I didn't look into it in much detail.

![screen shot 2019-01-24 at 12 45 26 pm](https://user-images.githubusercontent.com/666807/51707409-03e03b00-1fd6-11e9-8ce7-fcd088f847df.png)

**Comment by lilyball** [comment]
This sounds like a compiler bug. The `Error`-specific override should be considered more specific than the generic one. I'll dig into it further though.

**Comment by lilyball** [comment]
I've filed this as [SR-9753](https://bugs.swift.org/browse/SR-9753).
