### ISSUE TITLE
Should we adopt .map, .flatMap terminology?

### ISSUE THREAD

**Issue by lilyball** [lilyball/Tomorrowland#5]
Right now we use `.then`, `.catch`, `.recover`, and `.always`. Should we adopt more functional terminology, such as `.map`, `.flatMap`, `.mapError`, etc? This would mean less overloading.

**Comment by hborders** [comment]
I vote for `.map`, `.flatMap`, etc.

**Comment by hborders** [comment]
I think you spelled out the pros and cons very well.
